version: "3.7"
services:
  application:
    container_name: app
    build: .
    restart: always
    ports:
      - "8080:8080"
    links:
      - mysql:agrix-db
    environment:
      - DATABASE_HOST=jdbc:mysql://mysql:3306/agrix?createDatabaseIfNotExist=true #uma rede de containers usa-se o nome do servico (msql)
      - DATABASE_PORT=3306
      - DATABASE_USER=root
      - DATABASE_PASSWORD=root

  mysql:
    container_name: agrix-db
    image: mysql:8.0.32
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: agrix